### ISSUE TITLE
Hitting back on anything to go back to a page with a list makes a bunch of extra boxes

### ISSUE THREAD

**Issue by isajanusz** [ask-again-later/character-system#128]
I listed this as a bug earlier and it was resolved but I noticed it in places besides a player's characters page (example from screenshots - anything in the ST Tools tab) and I only said it was happening on the My Characters page. So just in case, I'm listing it again. In any case, my bad!

![screen shot 2017-04-02 at 7 44 26 pm](https://cloud.githubusercontent.com/assets/26777208/24592517/ceeead52-17dd-11e7-9d70-3358019dc257.png)
![screen shot 2017-04-02 at 7 44 41 pm](https://cloud.githubusercontent.com/assets/26777208/24592516/ceeb1e1c-17dd-11e7-8b61-27f2289c882d.png)
![screen shot 2017-04-02 at 7 47 04 pm](https://cloud.githubusercontent.com/assets/26777208/24592515/cee0f4b4-17dd-11e7-9d94-318121211c38.png)

**Comment by carlydotwebsite** [comment]
[wtf turbolinks](https://github.com/turbolinks/turbolinks/issues/106)

**Comment by carlydotwebsite** [comment]
Basically here it seems like the issue is a particularly odd interaction between Turbolinks and DataTables. Because of Turbolinks caching, the table is initialized more than once. I found articles/responses to that github issue linked above that suggested that we could hook into a turbolinks event to destroy the table before it's re-initialized, or use the destroy: true option to prevent it from being initialized more than once, but I couldn't get any of those to work.

**Comment by sublimemarch** [comment]
So, when I've encountered this problem in previous apps, we ended up deciding to just get rid of Turbolinks. Unless we have something that's actively using Turbonlinks, this app is small enough to not really need it.

**Comment by carlydotwebsite** [comment]
I'm 100% down with getting rid of turbolinks.
