### ISSUE TITLE
On character/form, there should be a countdown of how many points are left to spend in a category

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#37]

**Comment by carlydotwebsite** [comment]
okay, so I think i've figured out how to do the numerical calculations for all the validation; I'm just not sure where the best place is to display the counts and error messaging. Thoughts? (See branch 37-stat-validation)

**Comment by sublimemarch** [comment]
Hmm... good question. Maybe right under the title for that section? Or on the same line as the heading, but right aligned?

**Comment by carlydotwebsite** [comment]
Yeah, I like that idea; I think I'll try fiddling around with that.

The skills/special training one is a little odd since there's a pool for skills AND special trainings, and then there's the specific special training pool. Maybe it only visibly counts the overall one, and then adds a warning by the "special training" label if you have too many?
