### ISSUE TITLE
Advancement system

### ISSUE THREAD

**Issue by sublimemarch** [ask-again-later/character-system#66]
Details of advancement system should be filled in here.

**Comment by carlydotwebsite** [comment]
ok, so I think I have some ideas about how to do this without having to double-save character records—if there's a way we can save just the changed parts as a json record, we can then pull that up when we approve changes and have the character system apply the data in the object? If we just do .to_json on the params and store that.

**Comment by carlydotwebsite** [comment]
https://github.com/tim/activerecord-diff ok, so I think this gem might solve advancement:

* open characters for soft editing between seasons (need to figure out how to do this—maybe characters reopen for editing when they have > 0 points available?) (this will send an email to storytellers; possibly also send emails when XP is applied so that people know their characters are ok to edit?)
* if character is active, stop short of save, create a new object and diff with the old version
* save the diff in a database record, maybe calculate based on what the diff is how many points it adds up to in changes
* on the storyteller side, storyteller can see what changes the user has requested for their character and either approve it or reject it with a reason (this sends emails)
